configured_endpoints: 37
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/university-of-pittsburgh%2Fhubmap-entity-61fd4c3584c5b1d57d833a70dafe5cced15a91afb02638562a9412e2352c98a8.yml
